/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sajeel Ahmad
 */
public class AddBooking extends javax.swing.JFrame {

    /**
     * Creates new form AddBooking
     */
    public AddBooking() {
        initComponents();
        sourceCB();
        destinationCB();
       
    }
public void sourceCB()
    {
     try {
              Class.forName("com.mysql.jdbc.Driver");
            String dataBaseURL = "jdbc:mysql://localhost:3306/busM";
            Connection con;
            con = DriverManager.getConnection(dataBaseURL,"root","ntkxr0321");
            /*"INSERT INTO tablename(field1,field2) VALUES ('"+Text1+"','"+Text2*/
            Statement stat = con.createStatement();
            
            String selectQuery = "select Source from busDetails";
            
            ResultSet rs = stat.executeQuery(selectQuery);
            
            while(rs.next())
            {
              
                sourceCB.addItem(rs.getString("Source"));
            }
            
        } catch (ClassNotFoundException | SQLException e) {
                System.out.println(e);
        }   
    }

public void destinationCB()
    {
     try {
              Class.forName("com.mysql.jdbc.Driver");
            String dataBaseURL = "jdbc:mysql://localhost:3306/busM";
            Connection con;
            con = DriverManager.getConnection(dataBaseURL,"root","ntkxr0321");
            /*"INSERT INTO tablename(field1,field2) VALUES ('"+Text1+"','"+Text2*/
            Statement stat = con.createStatement();
            
            String selectQuery = "select Destination from busDetails";
            
            ResultSet rs = stat.executeQuery(selectQuery);
            
            while(rs.next())
            {
              
                destinationCB.addItem(rs.getString("Destination"));
            }
            
        } catch (ClassNotFoundException | SQLException e) {
                System.out.println(e);
        }   
    }


/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sourceCB = new javax.swing.JComboBox<>();
        destinationCB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        searchBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("ADD BOOKING");

        jLabel2.setText("Source:");

        destinationCB.setMinimumSize(new java.awt.Dimension(40, 40));
        destinationCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationCBActionPerformed(evt);
            }
        });

        jLabel4.setText("Date");

        searchBtn.setText("Submit");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Destination:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sourceCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(48, 48, 48)
                        .addComponent(destinationCB, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(572, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sourceCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destinationCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(452, 452, 452))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void destinationCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinationCBActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
      java.util.Date  departDate = (Date) date.getDate();
      SimpleDateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
      String departureDate = oDateFormat.format(departDate);
         try {
              Class.forName("com.mysql.jdbc.Driver");
            String dataBaseURL = "jdbc:mysql://localhost:3306/busM";
            Connection con;
            con = DriverManager.getConnection(dataBaseURL,"root","ntkxr0321");
            /*"INSERT INTO tablename(field1,field2) VALUES ('"+Text1+"','"+Text2*/
            Statement stat = con.createStatement();
            
            String selectQuery = "select * from busDetails where DepartureDate = '"+departureDate+"' and Source = '"+sourceCB.getSelectedItem()+"' and Destination = '"+destinationCB.getSelectedItem()+"'";
            
            ResultSet rs = stat.executeQuery(selectQuery);
            
            
            if(rs.next())
            {
              infoMessage("Record Found","Haehoo Express");
              SeatSelect sS = new SeatSelect(""+rs.getString("BusID")+"",""+(String) sourceCB.getSelectedItem()+"",""+(String) destinationCB.getSelectedItem()+"",Integer.parseInt(rs.getString("Price")));
               System.out.println(rs.getString("BusID"));
              
//              sS.getPrice(Integer.parseInt(rs.getString("Price")));
//              sS.getDestination((String) destinationCB.getSelectedItem());
//              sS.getSource((String) sourceCB.getSelectedItem());
//              sS.getID(rs.getString("BusID"));
              sS.setVisible(true);
              sS.setLocationRelativeTo(this);
              sS.setSize(600,600);
            }
            else if(!rs.next())
            {
                infoMessage("No Record Found","Haehoo Express");
            }
            
        } catch (ClassNotFoundException | SQLException e) {
                System.out.println(e);
        }   
            ShowBuses sB = new ShowBuses();
            sB.setVisible(true);
            sB.setLocationRelativeTo(this);
            sB.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            sB.setSize(550,550);
//
        //        
//try {
//            // TODO add your handling code here:
//            ShowBuses sB = new ShowBuses();
//            sB.setVisible(true);
//            sB.setLocationRelativeTo(this);
//            sB.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
//            sB.setSize(550,550);
//            
//            Class.forName("com.mysql.jdbc.Driver");
//            String dataBaseURL = "jdbc:mysql://localhost:3306/busM";
//            Connection con;
//            con = DriverManager.getConnection(dataBaseURL,"root","ntkxr0321");
//            /*"INSERT INTO tablename(field1,field2) VALUES ('"+Text1+"','"+Text2*/
//            Statement stat = con.createStatement();
//            
//            String selectQuery = "select BusID from busDetails";
//            
//            ResultSet rs = stat.executeQuery(selectQuery);
//            
//            searchTB.setModel(DbUtils.resultSetToTableModel(rs));
//            searchTB.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
//        } catch (ClassNotFoundException | SQLException ex) {
//            Logger.getLogger(AddBooking.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JComboBox<String> destinationCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox<String> sourceCB;
    // End of variables declaration//GEN-END:variables
public void infoMessage(String message, String title)
    {
        JOptionPane.showMessageDialog(this,message, title, JOptionPane.INFORMATION_MESSAGE);
    }
}
