
package bus.management;


import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sajeel Ahmad
 */
public class NewUser extends javax.swing.JFrame {

    /**
     * Creates new form NewUser
     */
    public NewUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fNameBtn = new javax.swing.JLabel();
        fNameTF = new javax.swing.JTextField();
        lNameBtn = new javax.swing.JLabel();
        lNameTF = new javax.swing.JTextField();
        uNameBtn = new javax.swing.JLabel();
        uNameTF = new javax.swing.JTextField();
        pWordTF = new javax.swing.JPasswordField();
        pWordbtn = new javax.swing.JLabel();
        eIdBtn = new javax.swing.JLabel();
        eIdTF = new javax.swing.JTextField();
        wUrlBtn = new javax.swing.JLabel();
        wUrlTF = new javax.swing.JTextField();
        regBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        alredyBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("New User Register");

        fNameBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        fNameBtn.setText("First Name");

        fNameTF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        fNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameTFActionPerformed(evt);
            }
        });

        lNameBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lNameBtn.setText("Last Name");

        lNameTF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameTFActionPerformed(evt);
            }
        });

        uNameBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        uNameBtn.setText("Username");

        uNameTF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        pWordTF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        pWordTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pWordTFFocusGained(evt);
            }
        });
        pWordTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pWordTFKeyPressed(evt);
            }
        });

        pWordbtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        pWordbtn.setText("Password");

        eIdBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        eIdBtn.setText("Email Id");

        eIdTF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        eIdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eIdTFActionPerformed(evt);
            }
        });

        wUrlBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        wUrlBtn.setText("WEB URL");

        wUrlTF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        regBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        regBtn.setText("Register");
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        alredyBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        alredyBtn.setText("Already have account? Sign In");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(193, 193, 193))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uNameBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fNameBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eIdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(regBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(alredyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(lNameBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(eIdTF)
                                    .addComponent(uNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pWordbtn)
                                    .addComponent(wUrlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lNameTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pWordTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wUrlTF, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameBtn)
                    .addComponent(fNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNameBtn)
                    .addComponent(lNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uNameBtn)
                    .addComponent(uNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pWordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pWordbtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eIdBtn)
                    .addComponent(eIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wUrlBtn)
                    .addComponent(wUrlTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alredyBtn)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void infoMessage(String message, String title)
    {
        JOptionPane.showMessageDialog(this,message, title, JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void fNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameTFActionPerformed

    private void lNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameTFActionPerformed

    private void eIdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eIdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eIdTFActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        fNameTF.setText("");
        lNameTF.setText("");
        uNameTF.setText("");
        pWordTF.setText("");
        eIdTF.setText("");
        wUrlTF.setText("");
    }//GEN-LAST:event_resetBtnActionPerformed

    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        // TODO add your handling code here:
        String firstName = fNameTF.getText();
        String lastName = lNameTF.getText();
        String userName = uNameTF.getText();
        String password = pWordTF.getText();
        String email = eIdTF.getText();
        String webURL = wUrlTF.getText();
        
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            String dataBaseURL = "jdbc:mysql://localhost:3306/busM";
            Connection con;
            con = DriverManager.getConnection(dataBaseURL,"root","ntkxr0321");
            /*"INSERT INTO tablename(field1,field2) VALUES ('"+Text1+"','"+Text2*/
            Statement stat = con.createStatement();
            String selectQuery = "select * from user_details where username ='"+userName+"' and password ='"+password+"'";
            
            ResultSet rs = stat.executeQuery(selectQuery);
            
            if(rs.next())
            {
                infoMessage("Already Registered!","Welcome dearie" );
            }
           else
            {
                         String insertQuery = "insert into user_details values(null,'"+firstName+"','"+lastName+"','"+userName+"','"+password+"','"+email+"','"+webURL+"')";
                         stat.executeUpdate(insertQuery);
                         UserLogin ln= new UserLogin();
                         infoMessage("Information is inserted!","Welcome");
                         dispose();
                         ln.setLocationRelativeTo(null);
                         ln.setVisible(true);
            }        
        }
        catch(ClassNotFoundException | SQLException e)
        {
            System.err.println(e);
        }
        
    }//GEN-LAST:event_regBtnActionPerformed

    private void pWordTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pWordTFFocusGained
        // TODO add your handling code here:
        boolean state= Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
        if(state == true)
        {
            JFrame frame = new JFrame("WARNING");
            JOptionPane.showMessageDialog(frame,
        "Caps Lock is on.",
        "Error!",
        JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_pWordTFFocusGained

    private void pWordTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pWordTFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pWordTFKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new NewUser().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alredyBtn;
    private javax.swing.JLabel eIdBtn;
    private javax.swing.JTextField eIdTF;
    private javax.swing.JLabel fNameBtn;
    private javax.swing.JTextField fNameTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lNameBtn;
    private javax.swing.JTextField lNameTF;
    private javax.swing.JPasswordField pWordTF;
    private javax.swing.JLabel pWordbtn;
    private javax.swing.JButton regBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel uNameBtn;
    private javax.swing.JTextField uNameTF;
    private javax.swing.JLabel wUrlBtn;
    private javax.swing.JTextField wUrlTF;
    // End of variables declaration//GEN-END:variables
}
